### ISSUE TITLE
transformer leaves URL untransformed

### ISSUE THREAD

**Issue by johnstonmatt** [remark-embedder/transformer-oembed#1]
- `@remark-embedder/transformer-oembed` version:
- `node` version: 12
- `npm` version: 6.14.8

Relevant code or config

```js
     const exampleMarkdown = `
        # My favorite YouTube video
        
        [This](https://www.youtube.com/watch?v=dQw4w9WgXcQ) is a great YouTube video.
        Watch it here:
        
        https://www.youtube.com/watch?v=dQw4w9WgXcQ
        
        Isn't it great!?
      `

      const htmlResult = await remark()
        .use(remarkEmbedder, {
          transformers: [oembedTransformer],
        })
        .use(htmlify)
        .process(exampleMarkdown);

      return {html: htmlResult.toString()};
```

What you did: after installing the plugin, importing it, and implementing it as above, it returns valid html, but the url has not been transformed.

What happened: the result is 
```html
<h1>My favorite YouTube video</h1>
<p><a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">This</a> is a great YouTube video.
Watch it here:</p>
<p>https://www.youtube.com/watch?v=dQw4w9WgXcQ</p>
<p>Isn't it great!?</p>
```

Reproduction repository: https://github.com/johnstonmatt/remark-oembedder-demo

Problem description: transformer not transforming

Suggested solution: 🤷‍♂️

**Comment by kentcdodds** [comment]
Hi @johnstonmatt,

Fixed: https://github.com/johnstonmatt/remark-oembedder-demo/pull/1

**Comment by johnstonmatt** [comment]
for some reason I though "CJS" meant closure script or something else I didn't know about lol
thanks @kentcdodds 🙏 !
