### ISSUE TITLE
Can this work client-side?

### ISSUE THREAD

**Issue by TiborUdvari** [remark-embedder/transformer-oembed#2]
Is this intended to be able to work client side with components such as `react-markdown`?
https://github.com/remarkjs/react-markdown

I'm trying to use it in a preview component for a blog writing component. 

I'm getting this module dependency error, although, again, I'm not sure if it's intended to work as I'm expecting.
```
Module not found: Can't resolve 'dns'
```

**Comment by kentcdodds** [comment]
Oh, interesting. I hadn't thought about supporting the client side. I think what we need to do is dynamically import the `make-fetch-happen` and the url module if fetch/URL aren't already defined. Would you be willing to make that work?

**Comment by NyakoFox** [comment]
Has there been any progress on this?

**Comment by kentcdodds** [comment]
Nobody's working on it
